name: IndexNow Submission
on:
  push:
    branches: [ main ]
jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: bojieyang/indexnow-action@v3
        with:
          sitemap-location: 'https://noelgrass.github.io/sitemap.xml'
          key: ${{ secrets.INDEXNOW_KEY }}
